name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag anieelorez/my-app:latest --tag anieelorez/my-app:$(date +%Y%m%d%H%M%S)

    - name: Push the Docker image
      run: |
        docker push anieelorez/my-app:latest
        docker push anieelorez/my-app:$(date +%Y%m%d%H%M%S)
